spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1025174607066-k8lblcigt8gbea0reu9naap4h6a4154c.apps.googleusercontent.com
            client-secret: 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