spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: IO9ap9rQVeo01eLYCjT71R7SevAfoCdV
            client-secret: HZUHlumcbaYCSClpzvBrFj2JcxAMsqRgggyo--R55HaCshtwFMdN3R4ZD18RqBVu
        provider:
          okta:
            issuer-uri: https://dev-be63episxvpoeg2s.us.auth0.com/
            # Or, optionally:            
            #authorization-uri https://dev-123-admin.okta.com/oauth2/v1/authorize
            #token-uri: https://dev-123-admin.okta.com/oauth2/v1/token
            #user-info-uri: https://dev-123-admin.okta.com/oauth2/v1/userinfo
            #jwk-set-uri: https://dev-123-admin.okta.com/oauth2/v1/keys